// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function AddFilterList(arg1:config.FilterList):Promise<void>;

export function AddFilterLists(arg1:Array<config.FilterList>):Promise<void>;

export function ExportDebugData():Promise<string>;

export function GetCAInstalled():Promise<boolean>;

export function GetFilterLists():Promise<Array<config.FilterList>>;

export function GetFilterListsByLocales(arg1:Array<string>):Promise<Array<config.FilterList>>;

export function GetFirstLaunch():Promise<boolean>;

export function GetIgnoredHosts():Promise<Array<string>>;

export function GetLocale():Promise<string>;

export function GetPACPort():Promise<number>;

export function GetPort():Promise<number>;

export function GetRouting():Promise<config.RoutingConfig>;

export function GetRules():Promise<Array<string>>;

export function GetTargetTypeFilterLists(arg1:config.FilterListType):Promise<Array<config.FilterList>>;

export function GetUpdatePolicy():Promise<config.UpdatePolicyType>;

export function GetUpstreamProxy():Promise<config.UpstreamProxyConfig>;

export function GetVersion():Promise<string>;

export function RemoveFilterList(arg1:string):Promise<void>;

export function RunMigrations():Promise<void>;

export function SetCAInstalled(arg1:boolean):Promise<void>;

export function SetIgnoredHosts(arg1:Array<string>):Promise<void>;

export function SetLocale(arg1:string):Promise<void>;

export function SetPACPort(arg1:number):Promise<void>;

export function SetPort(arg1:number):Promise<void>;

export function SetRouting(arg1:config.RoutingConfig):Promise<void>;

export function SetRules(arg1:Array<string>):Promise<void>;

export function SetUpdatePolicy(arg1:config.UpdatePolicyType):Promise<void>;

export function SetUpstreamProxy(arg1:config.UpstreamProxyConfig):Promise<void>;

export function ToggleFilterList(arg1:string,arg2:boolean):Promise<void>;
