// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFilterList(arg1) {
  return window['go']['config']['Config']['AddFilterList'](arg1);
}

export function AddFilterLists(arg1) {
  return window['go']['config']['Config']['AddFilterLists'](arg1);
}

export function ExportDebugData() {
  return window['go']['config']['Config']['ExportDebugData']();
}

export function GetCAInstalled() {
  return window['go']['config']['Config']['GetCAInstalled']();
}

export function GetFilterLists() {
  return window['go']['config']['Config']['GetFilterLists']();
}

export function GetFilterListsByLocales(arg1) {
  return window['go']['config']['Config']['GetFilterListsByLocales'](arg1);
}

export function GetFirstLaunch() {
  return window['go']['config']['Config']['GetFirstLaunch']();
}

export function GetIgnoredHosts() {
  return window['go']['config']['Config']['GetIgnoredHosts']();
}

export function GetLocale() {
  return window['go']['config']['Config']['GetLocale']();
}

export function GetPACPort() {
  return window['go']['config']['Config']['GetPACPort']();
}

export function GetPort() {
  return window['go']['config']['Config']['GetPort']();
}

export function GetRouting() {
  return window['go']['config']['Config']['GetRouting']();
}

export function GetRules() {
  return window['go']['config']['Config']['GetRules']();
}

export function GetTargetTypeFilterLists(arg1) {
  return window['go']['config']['Config']['GetTargetTypeFilterLists'](arg1);
}

export function GetUpdatePolicy() {
  return window['go']['config']['Config']['GetUpdatePolicy']();
}

export function GetUpstreamProxy() {
  return window['go']['config']['Config']['GetUpstreamProxy']();
}

export function GetVersion() {
  return window['go']['config']['Config']['GetVersion']();
}

export function RemoveFilterList(arg1) {
  return window['go']['config']['Config']['RemoveFilterList'](arg1);
}

export function RunMigrations() {
  return window['go']['config']['Config']['RunMigrations']();
}

export function SetCAInstalled(arg1) {
  return window['go']['config']['Config']['SetCAInstalled'](arg1);
}

export function SetIgnoredHosts(arg1) {
  return window['go']['config']['Config']['SetIgnoredHosts'](arg1);
}

export function SetLocale(arg1) {
  return window['go']['config']['Config']['SetLocale'](arg1);
}

export function SetPACPort(arg1) {
  return window['go']['config']['Config']['SetPACPort'](arg1);
}

export function SetPort(arg1) {
  return window['go']['config']['Config']['SetPort'](arg1);
}

export function SetRouting(arg1) {
  return window['go']['config']['Config']['SetRouting'](arg1);
}

export function SetRules(arg1) {
  return window['go']['config']['Config']['SetRules'](arg1);
}

export function SetUpdatePolicy(arg1) {
  return window['go']['config']['Config']['SetUpdatePolicy'](arg1);
}

export function SetUpstreamProxy(arg1) {
  return window['go']['config']['Config']['SetUpstreamProxy'](arg1);
}

export function ToggleFilterList(arg1, arg2) {
  return window['go']['config']['Config']['ToggleFilterList'](arg1, arg2);
}
